name: .NET CI

# When we push to the main branch or open a pull request into the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info ./test/CsvMole.SourceGenerators.Tests
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Not required for public repos
          file: ./CsvMole.SourceGenerators.Tests/lcov.info # Path to the coverage file
          flags: unittests # Optional, flags help differentiate coverage reports
          name: codecov-umbrella # Optional, name of the upload
